[build]
  base = "/"
  publish = "./"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/css/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
